services:
  app:
    entrypoint:
    - sleep
    - infinity
    image: jevo1900/devenv:rust
    init: true
    volumes:
    - type: bind
      source: /var/run/docker.sock
      target: /var/run/docker.sock
    ports:
      - "8000:8000"
    environment:
      - MONGO_URL=mongodb://db:27017/mydatabase
    depends_on:
      - db
    networks:
      - app-network
  db:
    image: mongo
    volumes:
      - mongodb_data_container:/data/db
    networks:
      - app-network
networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data_container: